In [2]:
#Varáveis Globais x Locais

nome = "José"

def EscreveGlob():
    print(f"{nome} está em aula!")

def EscreveInfoGlob():
    print(f"{nome} está estudando")

EscreveGlob()
EscreveInfoGlob()
nome = "Fernanda"

def EscreveLoc():
    nome = "Maria"
    print(f"{nome} está assistindo aula no SENAI!")

def EscreveInfoLoc():
    nome = "Maria"
    print(f"{nome} está na aula de Data Analytics com Python!")

EscreveLoc()
EscreveInfoLoc()

print (nome + ' É uma variável global e Maria é local!')


José está em aula!
José está estudando
Maria está assistindo aula no SENAI!
Maria está na aula de Data Analytics com Python!
Fernanda É uma variável global e Maria é local!


In [5]:
# Varargs - para passar "n" argumentos para uma função

def calcular_imposto(valor, perc_ir):
    ir = valor * perc_ir
    iss = valor * 0.05
    csll = valor * 0.0375
    pis = valor * 0.03
    return ir + iss + csll + pis

print(calcular_imposto(1000, perc_ir = 0.275))

def calcular_imposto2(valor, *args):
    total_imposto = 0
    for item in args:
        total_imposto += valor * item
    return total_imposto

print(calcular_imposto2(1000, 0.275, 0.05, 0.0375, 0.03))

392.5
392.5


In [1]:
def soma(*args):
    resultado = 0

    for x in args:
        resultado += x

    print(resultado)

soma(1,2,3,4,5,6)
soma(1,3)

import numpy as np
cont = 0
def Matrix3_3(cont, *args):
    Mat = np.zeros([int(len(args)/3), int(len(args)/3)])
    for x in range(int(len(args)/3)):
        for y in range(int(len(args)/3)):
            Mat[x][y] = args[cont]
            cont += 1
    print(Mat)

Matrix3_3(cont, 22,32,13,553,22,12,56,23,98)

21
4


[[ 22.  32.  13.]
 [553.  22.  12.]
 [ 56.  23.  98.]]


In [7]:
import math

def MenorNumero(*args):
    oMenor = math.inf
    for x in args:
        if (oMenor >= x):
            oMenor = x

    return (oMenor)

print('O menor número é: ' + str(MenorNumero(14,5,99,4,9,63)))

def MaiorNumero(*args):
    oMaior = -math.inf
    for x in args:
        if (oMaior <= x):
            oMaior = x
    return(oMaior)

print('O maior número é: '+ str(MaiorNumero(14,5,99,4,9,63)))

O menor número é: 4
O maior número é: 99


In [8]:
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

    def apresenta(self):
        print(f'{self.nome} tem {self.idade} anos!')

Pessoa1 = Pessoa("Joao", "15")
Pessoa2 = Pessoa("Maria", "18")

Pessoa.apresenta(Pessoa2)



Maria tem 18 anos!


In [10]:
class Fruta:
    def __init__(self, tipo, cor) -> None:
        self.tipo = tipo
        self.cor = cor
    def MostrarPropriedades(self):
        print(f'Sou um(a) {self.tipo} e minha cor é {self.cor}!')


NovaFruta = Fruta("Banana","Amarela")
NewFruit = Fruta("Melancia","Verde")

NovaFruta.MostrarPropriedades()
NewFruit.MostrarPropriedades()



Sou um(a) Banana e minha cor é Amarela!
Sou um(a) Melancia e minha cor é Verde!


In [12]:
class Animal():
    def __init__(self, nome, cor):
        self.__nome = nome
        self.__cor = cor
    def comer(self):
        print(f"O {self.__nome} {self.__cor} está comendo")

class Gato(Animal):
    def __init__(self, nome, cor):
        super().__init__(nome, cor)

class Cachorro(Animal):
    def __init__(self, nome, cor):
        super().__init__(nome, cor)

class Coelho(Animal):
    def __init__(self, nome, cor):
        super().__init__(nome, cor)

gato = Gato("Bichano","Branco")
cachorro = Cachorro("Totó","Preto")
coelho = Coelho("Pernalonga","Cinza")

gato.comer()
cachorro.comer()
coelho.comer()



O Bichano Branco está comendo
O Totó Preto está comendo
O Pernalonga Cinza está comendo
